routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::put('transactions/returnUnit/{transaction}', 'TransactionController@returnUnit')->name('transactions.return');
Route::put('transactions/cancelUnit/{transaction}', 'TransactionController@cancelRequest')->name('transactions.cancel');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');
Route::resource('units', 'UnitController');
Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;
use App\Unit;
use Auth;
use Str;
use App\Status;
class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Unit $unit, Request $request, Transaction $transaction)
    {   
        $this->authorize('view', $transaction);

        $statuses = [];
        $showTransaction = [];
        
        if(Auth::user()){
            if(Auth::user()->role_id == 1){
                $statuses = Status::whereIn('id', [1,2,3,6,7])->get();
                $showTransaction = Transaction::where('status_id', 1)->paginate(7);
                if ($request->status) {
                    if ($request->status == 1){
                        $showTransaction = Transaction::where('status_id', 1)->paginate(7);
                    } else if ($request->status == 2) {
                        $showTransaction = Transaction::where('status_id', 2)->paginate(7);
                    } else if ($request->status == 3) {
                        $showTransaction = Transaction::where('status_id', 3)->paginate(7);
                    } else if ($request->status == 6) {
                        $showTransaction = Transaction::where('status_id', 6)->paginate(7);
                    } else if ($request->status == 7) {
                        $showTransaction = Transaction::where('status_id', 7)->paginate(7);
                    }
                }
            } else {
                $statuses = Status::whereIn('id', [1,2,3,6,7])->get();
                $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 1)->paginate(7);
                if ($request->status) {
                    if ($request->status == 1){
                        $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 1)->paginate(7);
                    } else if ($request->status == 2) {
                        $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 2)->paginate(7);
                    } else if ($request->status == 3) {
                        $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 3)->paginate(7);
                    } else if ($request->status == 6) {
                        $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 6)->paginate(7);
                    } else if ($request->status == 7) {
                        $showTransaction = Transaction::where('user_id', Auth::user()->id)->where('status_id', 7)->paginate(7);
                    }
                }
            }
        }

        return view('transactions.index')
        ->with('statuses', $statuses )
        ->with('transactions', $showTransaction);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('errors.404');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Unit $unit, Transaction $transaction)
    {
        $this->authorize('create', $transaction);
        $user_id = Auth::user()->id;
        // date('Y-m-d-H-i-s')
        $reference_number = date('Y-m-d-(H:i:s)'). "-MTR-".Str::random(13);
        $request->validate([
            'borrow_start' => 'required|date',
            'borrow_end' => 'required|date|after:borrow_start'
        ]);

        // Transaction::create([
        //     'reference_number' => $reference_number,
        //     'unit_id' => $request->input('unit_id'),
        //     'user_id' => $user_id,
        //     'category_id' => $request->input('category_id'),
        //     'status_id' => 1,
        //     'borrowed_date' => $request->input('borrow_start'),
        //     'returned_date' => $request->input('borrow_end')
        // ]);

        $transaction->reference_number = $reference_number;
        $transaction->unit_id = $request->input('unit_id');
        $transaction->user_id = $user_id;
        $transaction->category_id = $request->input('category_id');
        $transaction->status_id = 1;
        $transaction->borrowed_date = $request->input('borrow_start');
        $transaction->returned_date = $request->input('borrow_end');
        $transaction->save();        

        $transaction->units()->attach(
            $request->input('unit_id'),
            [
                'borrow_start' => $request->input('borrow_start'),
                'borrow_end' => $request->input('borrow_end'),
                'transaction_id' => $transaction->id

            ]
        );

        $transaction->save();

        // $unit->where('id', $request->input('unit_id'))
        //     ->update(['status_id' => 5]);


        return redirect(route('units.index'))->with('request_success', 'Please wait for admin approval, Thank you!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        return view('errors.404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        return view('errors.404');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction, Unit $unit)
    {
        $this->authorize('update', $transaction);
        $transaction->status_id = 2;
        $transaction->save();

        $unit->where('id', $transaction->unit->id)
            ->update(['status_id' => 5]);

        return redirect(route('transactions.index'))->with('request_approved', 'APPROVED');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction, Unit $unit)
    {
        $this->authorize('delete', $transaction);
        $transaction->status_id = 6;
        $transaction->save();

        $unit->where('id', $transaction->unit->id)
            ->update(['status_id' => 4]);

        return redirect(route('transactions.index'))->with('request_rejected', 'REJECTED');
    }

    public function returnUnit(Transaction $transaction, Unit $unit) {
        $this->authorize('returnUnit', $transaction);
        $transaction->status_id = 3;
        $transaction->save();

        $unit->where('id', $transaction->unit->id)
            ->update(['status_id' => 4]);

        return redirect()->back()->with('unit_returned', 'RETURNED');
    }

    public function cancelRequest(Transaction $transaction, Unit $unit) {
        $this->authorize('cancelRequest', $transaction);
        $transaction->status_id = 7;
        $transaction->save();

        $unit->where('id', $transaction->unit->id)
            ->update(['status_id' => 4]);

        return redirect()->back()->with('request_canceled', 'CANCELED');
    }
}

resources/views/transactions/index.blade.php
@extends('layouts.app')

@if(Auth::user())
	@if(Auth::user()->role_id == 1)
		@section('content')
		<div class="ui container">
			<div class="ui doubling stackable grid container">
				<div class="four wide column">
					<div class="ui segment">
						<h1 class="ui header">Statuses</h1>
						<hr>
						<div class="ui middle aligned selection list">
							@foreach($statuses as $status)
							<a class="item" href="{{ route('transactions.index', ['status' => $status->id]) }}">
								<img class="ui avatar image" src="
								{{$status->id == 1 ? asset('images/pending.png') : '' }}
								{{$status->id == 2 ? asset('images/approved.png') : '' }}
								{{$status->id == 3 ? asset('images/returned.png') : '' }}
								{{$status->id == 6 ? asset('images/rejected1.png') : '' }}
								{{$status->id == 7 ? asset('images/canceled.png') : '' }}
								">
								<div class="content">
									<div class="header">{{ strtoupper($status->name) }}</div>
								</div>
							</a>
							@endforeach
						</div>
					</div>
				</div>
				<div class="twelve wide column">
					<div class="row">
						<div class="column">
							<h1>
							   {{!request()->status ? 'Pending' : ''}}
							   {{request()->status == 1 ? 'Pending' : ''}}
							   {{request()->status == 2 ? 'Approved' : ''}}
							   {{request()->status == 3 ? 'Returned' : ''}}
							   {{request()->status == 6 ? 'Rejected' : ''}}
							   {{request()->status == 7 ? 'Canceled' : ''}} Requests</h1>
						</div>
					</div>
					@section('scripts')
						@if(Session::has('request_approved'))
						<script>
							Swal.fire({
								position: 'top-end',
								icon: 'success',
								title: 'Request Approved!',
								showConfirmButton: false,
								timer: 1500
							})
						</script>
						@endif

						@if(Session::has('request_rejected'))
						<script>
							Swal.fire({
								position: 'top-end',
								icon: 'error',
								title: 'Request Rejected!',
								showConfirmButton: false,
								timer: 1500
							})
						</script>
						@endif

						@if(Session::has('unit_returned'))
						<script>
							Swal.fire({
								position: 'top-end',
								icon: 'success',
								title: 'Unit Returned!',
								showConfirmButton: false,
								timer: 1500
							})
						</script>
						@endif
					@endsection
					<div class="row">
						<table class="ui celled table text-center inverted 
							{{!request()->status ? 'teal' : ''}}
							{{request()->status == 1 ? 'teal' : ''}}
							{{request()->status == 2 ? 'green' : ''}}
							{{request()->status == 3 ? 'blue' : ''}}
							{{request()->status == 6 ? 'red' : ''}}
							{{request()->status == 7 ? 'purple' : ''}}
							table">
							<thead>
								<tr>
									<th>Reference_number</th>
									<th>Unit Name</th>
									<th>Request By</th>
									<th>Category</th>
									<th>Borrow Start</th>
									<th>Borrow End</th>
									@if(!request()->status ||request()->status == 1 || request()->status == 2)
									<th>Actions</th>
									@endif
									
								</tr>
							</thead>
							<tbody>
								@foreach($transactions as $transaction)
								<tr>
									<td>
										{{ $transaction->reference_number }}
									</td>
									<td>
										{{ $transaction->unit->name }}
									</td>
									<td>
										{{ $transaction->user->name }}
									</td>
									<td>
										{{ $transaction->unit->category->name }}
									</td>
									<td>
										{{ $transaction->borrowed_date->format('F d, Y') }}
									</td>
									<td>
										{{ $transaction->returned_date->format('F d, Y') }}
									</td>
									@if($transaction->status_id == 1)
									<td>
										<div class="ui small two buttons">
											<form action="{{ route('transactions.update', ['transaction' =>  $transaction->id ]) }}" method="POST">
												@csrf
												@method('PUT')
												<button class="green ui button"><i class="circle check outline icon"></i>Approve
												</button>
											</form>
											<form action="{{ route('transactions.destroy', ['transaction' => $transaction->id]) }}" method="POST">
												@csrf
												@method('DELETE')
												<button class="negative ui button"><i class="trash alternate outline icon"></i>Reject</button>
											</form>
										</div>
									</td>
									@elseif($transaction->status_id == 2)
									<td>
										<form action="{{ route('transactions.return', ['transaction' =>  $transaction->id ]) }}" method="POST">
											@csrf
											@method('PUT')
											<button class="yellow ui button"><i class="recycle icon"></i>Return
											</button>
										</form>
									</td>
									@endif
								</tr>
								@endforeach
							</tbody>
						</table>
						{{ $transactions->appends(request()->query())->links() }}
					</div>
				</div>
			</div>
		</div>
		@endsection

	@else
		@section('content')
			<div class="ui container">
				<div class="ui doubling stackable grid container">
					<div class="four wide column">
						<div class="ui segment">
							<h1 class="ui header">Statuses</h1>
							<hr>
							<div class="ui middle aligned selection list">
								@foreach($statuses as $status)
								<a class="item" href="{{ route('transactions.index', ['status' => $status->id]) }}">
									<img class="ui avatar image" src="
									{{$status->id == 1 ? asset('images/pending.png') : '' }}
									{{$status->id == 2 ? asset('images/approved.png') : '' }}
									{{$status->id == 3 ? asset('images/returned.png') : '' }}
									{{$status->id == 6 ? asset('images/rejected1.png') : '' }}
									{{$status->id == 7 ? asset('images/canceled.png') : '' }}
									">
									<div class="content">
										<div class="header">{{ strtoupper($status->name) }}</div>
									</div>
								</a>
								@endforeach
							</div>
						</div>
					</div>
					<div class="twelve wide column">
						<div class="row">
							<div class="column">
								<h1>My 
									   {{!request()->status ? 'Pending' : ''}}
									   {{request()->status == 1 ? 'Pending' : ''}}
									   {{request()->status == 2 ? 'Approved' : ''}}
									   {{request()->status == 3 ? 'Returned' : ''}}
									   {{request()->status == 6 ? 'Rejected' : ''}}
									   {{request()->status == 7 ? 'Canceled' : ''}} Requests</h1>
							</div>
						</div>

						<div class="row">
							<table class="ui celled table text-center inverted 
							{{!request()->status ? 'teal' : ''}}
							{{request()->status == 1 ? 'teal' : ''}}
							{{request()->status == 2 ? 'green' : ''}}
							{{request()->status == 3 ? 'blue' : ''}}
							{{request()->status == 6 ? 'red' : ''}}
							{{request()->status == 7 ? 'purple' : ''}}
							table">
								<thead>
									<tr>
										<th>Reference_number</th>
										<th>Unit Name</th>
										<th>Request By</th>
										<th>Category</th>
										<th>Borrow Start</th>
										<th>Borrow End</th>
										@if(!request()->status || request()->status == 1)
											<th>Action</th>
										@endif	
									</tr>
								</thead>
								<tbody>
									@foreach($transactions as $transaction)
									<tr>
										<td>
											{{ $transaction->reference_number }}
										</td>
										<td>
											{{ $transaction->unit->name }}
										</td>
										<td>
											{{ $transaction->user->name }}
										</td>
										<td>
											{{ $transaction->unit->category->name }}
										</td>
										<td>
											{{ $transaction->borrowed_date->format('F d, Y') }}
										</td>
										<td>
											{{ $transaction->returned_date->format('F d, Y') }}
										</td>
										@if(!request()->status || request()->status == 1)
										<td>
											<form action="{{ route('transactions.cancel', ['transaction' =>  $transaction->id ]) }}" method="POST">
												@csrf
												@method('PUT')
												<button class="red ui button"><i class="times circle outline icon"></i>Cancel
												</button>
											</form>
										</td>
										@endif
									</tr>
									@endforeach
								</tbody>
							</table>
							{{ $transactions->appends(request()->query())->links() }}
						</div>
					</div>
				</div>
			</div>
		@endsection
		@section('scripts')
			@if(Session::has('request_canceled'))
			<script>
				Swal.fire({
					position: 'top-end',
					icon: 'success',
					title: 'Request Canceled. Thank you!',
					showConfirmButton: false,
					timer: 1500
				})
			</script>
			@endif
		@endsection
	@endif
@else

@endif