routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::put('transactions/returnUnit/{transaction}', 'TransactionController@returnUnit')->name('transactions.return');
Route::put('transactions/cancelUnit/{transaction}', 'TransactionController@cancelRequest')->name('transactions.cancel');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');
Route::resource('units', 'UnitController');
Route::resource('transactions', 'TransactionController');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Unit extends Model
{
    use SoftDeletes;
    protected $fillable = ['name', 'serial_number', 'image', 'category_id'];

    public function category(){
    	return $this->belongsTo('App\Category');
    }
    
    public function status(){
    	return $this->belongsTo('App\Status');
    }

    public function transaction(){
    	return $this->belongsTo('App\Transaction');
    }
}

app/Http/Controllers/UnitsController.php
<?php

namespace App\Http\Controllers;

use App\Unit;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Support\Str;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Unit $unit)
    {
        // $this->authorize('view', $unit);
        
        if ($request->has('category')) {
            $showQuery = $unit->all()->where('category_id', '=', $request->category);
        } else {
            $showQuery = $unit::all();
        }

        return view('units.index')
            ->with('categories', Category::all())
            ->with('units', $showQuery);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Unit $unit)
    {
        $this->authorize('create', $unit);
        return view('units.create')->with('categories', Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Unit $unit)
    {
        $this->authorize('create', $unit);
        
        $request->validate([
            'name' => 'required|min:3|string',
            'serial_number' => 'required|string|min:6',
            'image' => 'required|image|max:3000|mimes:jpeg,jpg,png,gif',
            'category' => 'required'
        ]);

        $file = $request->file('image');
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $file_extension = $file->extension();
        
        $random_name = Str::random(10);

        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images', $new_file_name, 'public');

        Unit::create([
            'name' => $request->input('name'),
            'serial_number' => $request->input('serial_number'),
            'image' => $filepath,
            'category_id' => $request->input('category')
        ]);

        return redirect( route('units.create') )->with('unit_uploaded', 'UPLOADED');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Units  $units
     * @return \Illuminate\Http\Response
     */
    public function show(Unit $unit)
    {
        $this->authorize('view', $unit);
        return view('units.show')->with('unit', $unit);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Units  $units
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $this->authorize('update', $unit);
        return view('units.create')
            ->with('unit', $unit)
            ->with('categories', Category::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Units  $units
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unit $unit)
    {
        $this->authorize('update', $unit);
        $request->validate([
            'name' => 'required|min:3|string',
            'serial_number' => 'required|string|min:6',
        ]);

        if($unit->name == $request->input('name') &&
            $unit->serial_number == $request->input('serial_number') &&
            $unit->category_id == $request->input('category') &&
            !$request->hasFile('image')
        ) {
            $request->session()->flash('no_changes', 'No changes');
        }
        else {
            if($request->hasFile('image')) {
                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extension = $file->extension();
                
                $random_name = Str::random(10);

                $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images', $new_file_name, 'public');

                $unit->update([
                    'image' => $filepath
                ]);
            }
            $unit->update([
                'name' => $request->input('name'),
                'serial_number' => $request->input('serial_number'),
                'category_id' => $request->input('category')
            ]);
            $request->session()->flash('edit_unit', 'edit_unit');
        }
            return redirect( route('units.edit', ['unit' => $unit->id]) );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Units  $units
     * @return \Illuminate\Http\Response
     */
    public function destroy(Unit $unit)
    {   
        $this->authorize('delete', $unit);
        //delete function
        $unit->delete();
        return redirect( route('units.index'))->with('deleted_message', 'Unit Deleted');
    }

}

resources/views/units/create.blade.php
@extends('layouts.app')

@section('content')

<div class="ui raised very padded text container segment my-5">
    <h1 class="text-center">
        {{ isset($unit) ? 'Edit Unit' : 'Add New Unit' }}
    </h1>
    <hr>
    
    @if ($errors->any())
        <div class="ui error message">
            <div class="header">
                There were error with your submission
            </div>
            <ul class="list">
                @foreach($errors->all() as $error)
                    {{-- <li>{{ $errors->all() }}</li> --}}
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form class="ui form" method="POST" action="{{ isset($unit) ? route('units.update', ['unit' => $unit->id   ]) : route('units.store') }}" enctype="multipart/form-data">
        @csrf
        @if(isset($unit))
            @method('PUT')
        @endif
        <div class="field">
            <label for="category">Unit Name</label>
            <input type="text" name="name" placeholder="Unit Name" 
            value="{{ isset($unit) ? $unit->name : old('name') }}"
            >
        </div>

        <div class="field">
            <label for="serial_number">Serial Number</label>
            <input name="serial_number" placeholder="Serial Number...." value="{{ isset($unit) ? $unit->serial_number : old('serial_number') }}">
        </div>

        <div class="field">
            <label for="category_id">Category</label>
            <select name="category" id="category_id">
                @foreach($categories as $category)
                    <option value="{{ $category->id }}" 
                        @if( isset($unit))
                        {{$unit->category_id == $category->id ? 'selected' : ''}}
                        @endif
                        >
                        {{ strtoupper($category->name) }}
                    </option>
                @endforeach

            </select>
        </div>

        @if(isset($unit))
            <img class="ui medium centered image fluid" src="{{ url('/public/'.$unit->image) }}">
        @endif

        <div class="ui float-left transparent field left icon input">
            <input type="file" class="form-control-file" name="image" placeholder="Search...">
            <i class="image icon"></i>
        </div>  
        <button class="ui teal large button right floated" type="submit">
            {{ isset($unit) ? 'Update' : 'Add Unit' }}
        </button>
    </form>
</div>

@endsection

@section('scripts')

    @if(Session::has('unit_uploaded'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Unit Added',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif

    @if(Session::has('edit_unit'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Unit Updated!',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif

    @if(Session::has('no_changes'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'info',
                title: 'There were no changes in the unit details!',
                showConfirmButton: false,
                timer: 3000
            })
        </script>
    @endif



@endsection

resources/views/units/index.blade.php
@extends('layouts.app')


@if(Auth::user() && Auth::user()->role_id == 1)
	@section('content')
		<div class="ui container">
			<div class="ui doubling stackable grid container">
				<div class="four wide column">
					<div class="ui segment">
						<h1 class="ui header">Categories</h1>
						<hr>
						<div class="ui middle aligned selection list">
							@foreach($categories as $category)
							<a class="item" href="{{ route('units.index', ['category' => $category->id]) }}">
								<img class="ui avatar image" src="{{ url('/public/'.$category->image) }}">
								<div class="content">
									<div class="header">{{ $category->name }}</div>
								</div>
							</a>
							@endforeach
						</div>
					</div>
				</div>
				<div class="twelve wide column">
					<div class="row">
						<div class="column">
							<h1>Items</h1>
						</div>
						<div class="column right floated">
							<a href="{{ route('units.create') }}" class="green ui button"><i class="plus circle icon"></i>Add Unit</a>
						</div>
					</div>
					<div class="row">
						<table class="ui celled table text-center">
							<thead>
								<tr>
									<th>Image</th>
									<th>Name</th>
									<th>Serial Number</th>
									<th>Category</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								@foreach($units as $unit)
								<tr>
									<td>
										<img class="ui tiny image centered" src="{{ url('/public/'.$unit->image) }}">
									</td>
									<td>{{ $unit->name }}</td>
									<td>{{ $unit->serial_number }}</td>
									<td>{{ $unit->category->name }}</td>
									<td>
										<div class="ui three buttons">
											<a class="green ui button" href="{{ route('units.show', ['unit' => $unit->id]) }}"><i class="newspaper outline icon"></i>Details
											</a>

											<form action="{{ route('units.destroy', ['unit' => $unit->id]) }}" method="POST">
												@csrf
												@method('DELETE')
												<button class="negative ui button"><i class="trash alternate outline icon"></i>Delete &nbsp;</button>

											</form>
											<a href="{{ route('units.edit', ['unit' =>  $unit->id ]) }}" class="teal ui button"><i class="edit outline icon"></i>Update</a>
										</div>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	@endsection

@else
	@section('content')
		<div class="ui container">
			<div class="ui doubling stackable grid container">
				<div class="four wide column">
					<div class="ui segment">
						<h1 class="ui header">Categories</h1>
						<hr>
						<div class="ui middle aligned selection list">
							@foreach($categories as $category)
							<a class="item" href="{{ route('units.index', ['category' => $category->id]) }}">
								<img class="ui avatar image" src="{{ url('/public/'.$category->image) }}">
								<div class="content">
									<div class="header">{{ $category->name }}</div>
								</div>
							</a>
							@endforeach
						</div>
					</div>
				</div>
				
				<div class="twelve wide column">
					<div class="row">
						<h1>Items</h1>
					</div>
					<hr>
					<div class="ui grid stackable">
						<div class="four column row doubling stackable">
							@foreach($units as $unit)
							<div class="column">
								<div class="ui fluid special cards centered">
									<div class="card mb-4">
										<div class="blurring dimmable image">
											<div class="ui dimmer">
												<div class="content">
													<div class="center">
														@if($unit->status->id != 5)
														<button type="button" class="ui teal button" data-toggle="modal" data-target="#show_request_modal{{$unit->id}}">
															<i class="add icon"></i>
															Request Unit
														</button>
														@else
														<label class="ui red label">
															<i class="times icon"></i>
															Not Available
														</label>
														@endif
													</div>
												</div>
											</div>
											<div class="ui fluid big image">
												<img style="height:200px;" src="{{ url('/public/'.$unit->image) }}">
											</div>
										</div>
										<div class="content">
											<div class="header">{{ $unit->name }}</div>
											<div class="description center aligned">
												<label class="ui label {{$unit->status->id == 5 ? 'yellow' : 'green'}} ">
													<i class="{{$unit->status->id == 5 ? 'times' : 'check'}} circle outline icon"></i>
													{{ strtoupper($unit->status->name) }}
												</label>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- The Modal -->
							<div class="modal fade" id="show_request_modal{{$unit->id}}">
								<div class="modal-dialog modal-dialog-centered show">
									<div class="modal-content">
										<!-- Modal Header -->
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
										</div>

										<!-- Modal body -->
										<div class="modal-body">
											<h2 class="modal-title text-center">{{ $unit->name }}</h2>
											<hr>
											<div class="ui fluid cards centered">
												<div class="card mb-4">
													<div class=image">
														<div class="content">
															<div class="center">

															</div>
														</div>
														<div class="ui fluid big image">
															<img style="height:200px;" src="{{ url('/public/'.$unit->image) }}">
														</div>
													</div>
													<div class="content">
														<div class="header"></div>
														<div class="description center aligned">
															<label class="ui label green">
																<i class="check circle outline icon"></i>Available
															</label>
														</div>
													</div>


												</div>
											</div>
											<hr>
											<form action="{{ route('transactions.store') }}" method="POST">
												@csrf
												<input type="hidden" name="unit_id" value="{{ $unit->id }}">
												<input type="hidden" name="category_id" value="{{ $unit->category->id }}">
												<div class="ui form">
													<div class="two fields">
														<div class="field">
															<label>Borrowed Date Start</label>
															<input type="date" name="borrow_start" value="{{ old('borrow_start', date('m/d/Y')) }}" placeholder="Borrowed Date Start">
														</div>
														<div class="field">
															<label>Return Date</label>
															<input type="date" name="borrow_end" value="{{ old('borrow_end', date('m/d/Y')) }}" placeholder="Return Date">
														</div>
													</div>
												</div>
												<button class="btn btn-success btn-block">Request</button>
											</form>
										</div>
										<!-- Modal footer -->
										<div class="modal-footer">
											<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>        
										</div>
									</div>
								</div>
							</div>
							{{-- END OF MODAL --}}
							@endforeach
						</div>
					</div>
				</div>
			</div>
		</div>
	@endsection

@endif

@section('scripts')
@if(Session::has('deleted_message'))
	<script>
		Swal.fire({
			position: 'top-end',
			icon: 'error',
			title: 'Unit Deleted!',
			showConfirmButton: false,
			timer: 1500
		})
	</script>
@endif
@if(Session::has('request_success'))
<script>
	Swal.fire({
		position: 'top-end',
		icon: 'success',
		title: 'Request Success. Please wait for admin aproval, Thank you!',
		showConfirmButton: false,
		timer: 1500
	})
</script>
@endif

@if($errors->any())
<script>
	Swal.fire({
		position: 'top-end',
		icon: 'warning',
		title: "Request Failed. {{ $errors->first() }} Thank you!",
		showConfirmButton: false,
		timer: 6000
	})
</script>
@endif

<script>
	$('.special.cards .image').dimmer({
		on: 'hover'
	});
</script>
@endsection

resources/views/units/show.blade.php
@extends('layouts.app')

@section('content')

<div class="ui raised very padded text container segment my-5">
    <h1 class="text-center">
        Details
    </h1>
    <hr>
    <div class="ui raised container segment">
    	<img class="ui centered medium image" src="{{ url('/public/'.$unit->image) }}">
    	

    </div>
    	<h3 class="ui header">Name</h3>
    	<div class="ui raised container segment">
    		  <strong> {{ $unit->name }} </strong>    		
    	</div>

		<h2 class="ui header">Serial Number: 
            <div class="ui olive label">
                {{ $unit->serial_number }}
            </div>
        </h2>
        
        <h2 class="ui header">Category:
            <div class="ui teal label">
                {{ $unit->category->name }}
            </div>
        </h2>

        <h2>Status:
            <div class="ui {{$unit->status->id == 4 ? 'green' : 'red' }} label">
                {{ strtoupper($unit->status->name) }}
            </div>  
        </h2>             		

    	<hr>
		<div class="ui center aligned basic segment">
        	<div class="big ui buttons">
        		<form action="{{ route('units.destroy', ['unit' => $unit->id]) }}" method="POST">
        			@csrf
        			@method('DELETE')
        			<button class="negative ui button"><i class="trash alternate outline icon"></i>Delete</button>

        		</form>
        		<div class="or"></div>
        		<a href="{{ route('units.edit', ['unit' =>  $unit->id ]) }}" class="teal ui button"><i class="edit outline icon"></i>Update</a>
        	</div>
    	</div>
</div>

@endsection