routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::put('transactions/returnUnit/{transaction}', 'TransactionController@returnUnit')->name('transactions.return');
Route::put('transactions/cancelUnit/{transaction}', 'TransactionController@cancelRequest')->name('transactions.cancel');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');
Route::resource('units', 'UnitController');
Route::resource('transactions', 'TransactionController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{	
	use SoftDeletes;
    protected $fillable = ['name', 'description', 'image'];
    //

    public function units(){
    	return $this->hasMany('App\Unit');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Category $category)
    {
        $this->authorize('view', $category);
        return view('categories.index', ['categories' => Category::all() ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category)
    {
        $this->authorize('view', $category);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category)
    {
        $this->authorize('view', $category);
        $request->validate([
            'name' => 'required|string|unique:categories,name|min:3',
            'description' => 'required|string',
            'image' => 'required|image|max:3000|mimes:jpeg,jpg,png,gif',
        ]);

        $file = $request->file('image');
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $file_extension = $file->extension();
        
        $random_name = Str::random(10);

        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images', $new_file_name, 'public');

        
        Category::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'image' => $filepath
        ]);

        return redirect( route('categories.create') )->with('category_uploaded', 'Category Uploaded');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $this->authorize('view', $category);
        return view('categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('view', $category);
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('view', $category);
        $request->validate([
           // 'name' => 'required|string|unique:categories,name|min:3',
           'description' => 'required|string',
        ]);
        
        $file = $request->file('image');

        if($file){
            $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $file_extension = $file->extension();

            $random_name = Str::random(10);

            $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

            $filepath = $file->storeAs('images', $new_file_name, 'public');
            $category->update([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'image' => $filepath
            ]);    
        } else {
            $category->update([
                'name' => $request->input('name'),
                'description' => $request->input('description')
            ]);    
        }
        
        return redirect( route('categories.index'))
            ->with('category_updated', $category->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('view', $category);
        $category->delete();
        return redirect( route('categories.index'))->with('deleted_message', 'Category Deleted');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class="ui raised very padded text center aligned container segment my-5">
    <h1 class="center">
        {{ isset($category) ? 'Edit Category' : 'Add New Category' }}
    </h1>
    <hr>
    @if ($errors->any())
    <div class="ui error message">
        <div class="header">
            There were error with your submission
        </div>
        <ul class="list">
            @foreach($errors->all() as $error)
                {{-- <li>{{ $errors->all() }}</li> --}}
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <form class="ui form" method="POST" action="{{ isset($category) ? route('categories.update', ['category' => $category->id   ]) : route('categories.store') }}" enctype="multipart/form-data">
        @csrf
        @if(isset($category))
            @method('PUT')
        @endif
        <div class="field">
            <label for="category">Category Name:</label>
            <input type="text" name="name" placeholder="Category Name" 
            value="{{ isset($category) ? $category->name : old('name') }}"
            >
        </div>

        <div class="field">
            <label for="description">Description</label>
            <textarea name="description" cols="30" rows="10" placeholder="Description....">{{ isset($category) ? $category->description : old('description') }}</textarea>
        </div>
        <div class="ui float-left transparent field left icon input">
            <input type="file" class="form-control-file" name="image" placeholder="Search...">
            <i class="image icon"></i>
        </div>  
        <button class="ui teal large button right floated" type="submit">
            {{ isset($category) ? 'Update' : 'Add Category' }}
        </button>
    </form>
</div>

@endsection

@section('scripts')

    @if (Session::has('category_uploaded'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Category Uploaded!',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui segment container">
        <h1 class="text-center">CATEGORIES</h1>
        <div class="ui grid">
            <div class="sixteen wide mobile eight wide computer column">
                <img class="ui fluid image centered" src="{{ asset('images/categories_img.png') }}">
            </div>
            <div class="sixteen wide mobile eight wide computer column mt-5">

                <a class="ui black link" id="add-category" name="add-category" href="{{ route('categories.create') }}">
                <div class="ui right floated small teal labeled icon button mb-2">
                    <i class="plus circle icon"></i>
                        Add Category
                </div>
                </a>
                <table class="ui table">
                    <thead>
                        <tr>
                            <th class="four wide">Name</th>
                            <th class="six wide text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categories as $category)
                        <tr @if(Session::has('category_updated') && Session::get('category_updated') == $category->id)
                            class='ui inverted olive table'
                            @endif>
                            <th>{{ $category->name }}</th>
                            <td>
                                <div class="ui three buttons">
                                    <a class="green ui button" href="{{ route('categories.show', ['category' => $category->id]) }}"><i class="newspaper outline icon"></i>Details</a>
                                    <form action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="negative ui button"><i class="trash alternate outline icon"></i>Delete</button>
                                    
                                    </form>
                                    <a href="{{ route('categories.edit', ['category' =>  $category->id ]) }}" class="teal ui button"><i class="edit outline icon"></i>Update</a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    @if(Session::has('category_updated'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Category Updated!',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif

    @if(Session::has('deleted_message'))
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'error',
                title: 'Category Deleted!',
                showConfirmButton: false,
                timer: 1500
            })
        </script>            
    @endif

@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')

<div class="ui raised very padded text container segment my-5">
    <h1 class="text-center">
        Details
    </h1>
    <hr>
    <div class="ui raised container segment">
    	<img class="ui centered medium image" src="{{ url('/public/'.$category->image) }}">
    	

    </div>
    	<h3 class="ui header">Name</h3>
    	<div class="ui raised container segment">
    		  <strong> {{ $category->name }} </strong>    		
    	</div>

		<h2 class="ui header">Description</h2>
    	<div class="ui raised container segment">
    		<p>{{ $category->description }}</p>    		
    	</div>
    	<hr>

		<div class="ui center aligned basic segment">
    	<div class="big ui buttons">
    		<form action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="POST">
    			@csrf
    			@method('DELETE')
    			<button class="negative ui button"><i class="trash alternate outline icon"></i>Delete</button>

    		</form>
    		<div class="or"></div>
    		<a href="{{ route('categories.edit', ['category' =>  $category->id ]) }}" class="teal ui button"><i class="edit outline icon"></i>Update</a>
    	</div>
    	</div>
</div>

@endsection